In [5]:
# Covering the first part of EDA 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

data = {
    'customers': ['kibe', 'Muiruri', 'Kinya', 'wamalawa', 'Achieng', 'Otieno'],
    'sales':     [240, np.nan, 650, 450, np.nan, 300],      # np.nan in positions 1 and 4
    'Revenue':   [200, 300, np.nan, 400, 250, np.nan]        # np.nan in positions 2 and 5
}
df = pd.DataFrame(data)

  customers  sales  Revenue
0      kibe  240.0    200.0
1   Muiruri    NaN    300.0
2     Kinya  650.0      NaN
3  wamalawa  450.0    400.0
4   Achieng    NaN    250.0
5    Otieno  300.0      NaN

In [12]:
#  finding the null elements from the dataset 
df.isnull()

   customers  sales  Revenue
0      False  False    False
1      False   True    False
2      False  False     True
3      False  False    False
4      False   True    False
5      False  False     True

In [13]:
df.isnull().sum() #calculates the total number of null cells in each of the columns

customers    0
sales        2
Revenue      2
dtype: int64

In [14]:
df.isnull().sum().sum()  # total missing values in whole df

4

In [15]:
df['sales'].isnull().sum()

2

In [18]:
#  dropping the null elements in the dataframe 
df.dropna()
#  dropping any row with any missing value

  customers  sales  Revenue
0      kibe  240.0    200.0
3  wamalawa  450.0    400.0

In [19]:
df.dropna(subset=['sales'])      # drop rows missing in 'sales' only

  customers  sales  Revenue
0      kibe  240.0    200.0
2     Kinya  650.0      NaN
3  wamalawa  450.0    400.0
5    Otieno  300.0      NaN

In [20]:
df.dropna(axis=1)                # drop columns instead of rows

  customers
0      kibe
1   Muiruri
2     Kinya
3  wamalawa
4   Achieng
5    Otieno

In [21]:
df.dropna(thresh=2)              # keep rows with at least 2 non-null values

  customers  sales  Revenue
0      kibe  240.0    200.0
1   Muiruri    NaN    300.0
2     Kinya  650.0      NaN
3  wamalawa  450.0    400.0
4   Achieng    NaN    250.0
5    Otieno  300.0      NaN

In [22]:
#  proceeding with filling NAN columns 
#  filling with the zero value 
df.fillna(0)

  customers  sales  Revenue
0      kibe  240.0    200.0
1   Muiruri    0.0    300.0
2     Kinya  650.0      0.0
3  wamalawa  450.0    400.0
4   Achieng    0.0    250.0
5    Otieno  300.0      0.0

In [35]:
#  filling the sales and revenue column with the average of each column
df['sales'].fillna(df['sales'].mean())
df['Revenue'].fillna(df['Revenue'].mean())

0    200.0
1    300.0
2    287.5
3    400.0
4    250.0
5    287.5
Name: Revenue, dtype: float64

In [36]:
# . Interpolation — estimate missing values from surrounding data

# This is smarter than a flat fill — it guesses based on the pattern of nearby values.
df['sales'].interpolate()
print(df)
# Essence: Interpolation assumes your data has a trend or continuity — good for time series, sensor readings, prices over time. Bad for categorical or "jumpy" data where there's no real relationship between adjacent rows (like your customers column — interpolating between two names makes no sense).

  customers  sales  Revenue
0      kibe  240.0    200.0
1   Muiruri  445.0    300.0
2     Kinya  650.0      NaN
3  wamalawa  450.0    400.0
4   Achieng  375.0    250.0
5    Otieno  300.0      NaN

In [37]:
df['Revenue'].ffill()   # forward fill: carry last known value forward

0    200.0
1    300.0
2    300.0
3    400.0
4    250.0
5    250.0
Name: Revenue, dtype: float64

In [38]:
df['Revenue'].bfill() #backward fill : borrow the next known value

0    200.0
1    300.0
2    400.0
3    400.0
4    250.0
5      NaN
Name: Revenue, dtype: float64